name: Python CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run_tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        python-version: ["3.11"]
        node-version: ["10"]
        toxenv: [django42, quality, pii_check, rst_validation]

    steps:
      - uses: actions/checkout@v1
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pip
        run: pip install -r requirements/pip-tools.txt

      - name: Install requirements
        run: pip install -r requirements/ci.txt

      - name: Run tests
        env:
          TOXENV: ${{ matrix.toxenv }}
        run: tox

      - name: Run Coverage
        if: matrix.toxenv == 'django42'
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ github.token }}
          MINIMUM_GREEN: 95
          MINIMUM_ORANGE: 84
          ANNOTATE_MISSING_LINES: true
          ANNOTATION_TYPE: error
          uses: codecov/codecov-action@v2

      - name: Report coverage
        id: coverage_comment
        if: matrix.toxenv == 'django42'
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ github.token }}
          MINIMUM_GREEN: 95
          MINIMUM_ORANGE: 84
          ANNOTATE_MISSING_LINES: true
          ANNOTATION_TYPE: error
          uses: codecov/codecov-action@v2

      - name: Store pll request coverage comment to post in another action
        uses: actions/upload-artifact@v4
        if: steps.coverage_comment.outputs.COMMENT_FILE_WRITTEN == 'true'
        with:
          # If you use a different name, update COMMENT_ARTIFACT_NAME accordingly
          name: python-coverage-comment-action
          # If you use a different name, update COMMENT_FILENAME accordingly
          path: python-coverage-comment-action.txt